### ISSUE TITLE
フォーム設定に追加クラスが登録できない

### ISSUE THREAD

**Issue by lackxxx** [inc2734/snow-monkey-forms#108]
*バージョン環境*
- WordPress 5.7.2
- Snow Monkey Forms 1.5.3

症状としては表題の通りで、フォーム設定にて追加クラスが登録できません。

再現手順は
- フォーム下部にある高度な設定を選択
- 追加CSSクラス で個別クラスを登録
です。

カスタムテンプレートを使用した状態で発生しましたので、デフォルトテンプレートに切り替えバニラな状態で実施しましたが再現しました。

**Comment by inc2734** [comment]
ご報告ありがとうございます！後日確認しますね。
