### ISSUE TITLE
パターンを開くと[エディターで予期しないエラーが発生しました。]となってしまう。

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-forms#130]
~~ブロックの選択で Snow Monkey Forms に該当しないブロックが表示されている際、~~ ← 多分、関係ない。

ブロックをEnterキーで追加ブロックを追加する際に、すべて表示→左のブロック選択パネルから「パターン」を開くと
[エディターで予期しないエラーが発生しました。]となってしまう。

通常のブロックエディタや他のカスタム投稿タイプでは問題ないので Snow Monkey Formsのフォームを編集している時だけ発生してる気がします。
Snow Monkey Formsのフォームでの（カスタム投稿タイプ？）エディタ画面の場合、ブロックパターンをエディタから選択できないようにするなどで対策できないか？
（…確か、エディタのパターン部分を消す方法ってありましたよね？だいぶ前過ぎて覚えてないけど）

■ 確認したこと
・テーマは関係なし
・WordPress 6.1 βでも起こる
・他のエディタ画面では起こらない
・Snow Monkey Forms 以外のブロック（Snow Monkey blocksなどのブロック）を配置しているなどは関係ない

**Comment by inc2734** [comment]
Snow Monkey Forms のフォーム編集画面は入力画面用・完了画面用のコンテンツの入力欄が表示されていて、その入力欄は消されないようになっています。それは `register_post_type()` の `template` で定義されていて、`template_lock` で消されないようにしているわけですが、どうも `template_lock` が指定されているとこの不具合が発生してしまうようです。

https://github.com/inc2734/snow-monkey-forms/blob/master/snow-monkey-forms.php#L281

大枠のほうではなくてブロック（入力画面ブロック・完了画面ブロック）のほうでロックするとこの不具合は発生しないみたいなので、その方向で変更を入れてみます！
